"""Update workflow model to use graph structure

Revision ID: 3962101bb47b
Revises: 3e2f385b80a2
Create Date: 2026-01-23 17:26:27.861405

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3962101bb47b'
down_revision: Union[str, Sequence[str], None] = '3e2f385b80a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # First, add the new columns as nullable
    op.add_column(
        'workflows', sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        'workflows', sa.Column('version', sa.Integer(), server_default='1', nullable=False)
    )
    op.add_column(
        'workflows',
        sa.Column('data_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    )

    # Migrate existing data: set default empty graph for existing workflows
    op.execute(
        'UPDATE workflows SET graph = \'{"nodes": [], "connections": []}\' WHERE graph IS NULL'
    )

    # Now make the graph column non-nullable
    op.alter_column('workflows', 'graph', nullable=False)

    # Drop the old tables
    op.drop_index(op.f('ix_connections_source_node_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_target_node_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_workflow_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_nodes_plugin_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_workflow_id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'data_hash')
    op.drop_column('workflows', 'version')
    op.drop_column('workflows', 'graph')
    op.create_table(
        'nodes',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            'config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column(
            'ui', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            'is_deleted',
            sa.BOOLEAN(),
            server_default=sa.text('false'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('plugin_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('nodes_pkey')),
    )
    op.create_index(op.f('ix_nodes_workflow_id'), 'nodes', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_nodes_plugin_id'), 'nodes', ['plugin_id'], unique=False)
    op.create_table(
        'connections',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('source_node_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('target_node_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('source_output', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('target_input', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('connections_pkey')),
    )
    op.create_index(
        op.f('ix_connections_workflow_id'), 'connections', ['workflow_id'], unique=False
    )
    op.create_index(
        op.f('ix_connections_target_node_id'), 'connections', ['target_node_id'], unique=False
    )
    op.create_index(
        op.f('ix_connections_source_node_id'), 'connections', ['source_node_id'], unique=False
    )
    # ### end Alembic commands ###
