"""add_plugin_id_to_nodes

Revision ID: 3e2f385b80a2
Revises: 89a90219e9f3
Create Date: 2026-01-22 15:21:08.196684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2f385b80a2'
down_revision: Union[str, Sequence[str], None] = '89a90219e9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('plugin_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_nodes_plugin_id'), 'nodes', ['plugin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_plugin_id'), table_name='nodes')
    op.drop_column('nodes', 'plugin_id')
    # ### end Alembic commands ###
