"""Initial migration with all models and soft delete

Revision ID: 559fb8d7205a
Revises: 
Create Date: 2025-12-05 14:30:13.714704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '559fb8d7205a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_application_id'), 'api_keys', ['application_id'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('applications',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_workflow_id'), 'applications', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_applications_workspace_id'), 'applications', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('bpm_approvals',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('process_instance_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('approver_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', 'TRANSFER', 'DELEGATE', 'RETURN', name='approvalaction'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('transfer_to', sa.Uuid(), nullable=True),
    sa.Column('transfer_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bpm_approvals_approver_id'), 'bpm_approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_bpm_approvals_process_instance_id'), 'bpm_approvals', ['process_instance_id'], unique=False)
    op.create_index(op.f('ix_bpm_approvals_task_id'), 'bpm_approvals', ['task_id'], unique=False)
    op.create_index(op.f('ix_bpm_approvals_workspace_id'), 'bpm_approvals', ['workspace_id'], unique=False)
    op.create_table('bpm_form_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_instance_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('form_definition_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bpm_form_data_process_instance_id'), 'bpm_form_data', ['process_instance_id'], unique=False)
    op.create_index(op.f('ix_bpm_form_data_task_id'), 'bpm_form_data', ['task_id'], unique=False)
    op.create_index(op.f('ix_bpm_form_data_workspace_id'), 'bpm_form_data', ['workspace_id'], unique=False)
    op.create_table('bpm_form_definitions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('form_schema', sa.JSON(), nullable=True),
    sa.Column('ui_schema', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bpm_form_definitions_key'), 'bpm_form_definitions', ['key'], unique=True)
    op.create_index(op.f('ix_bpm_form_definitions_workspace_id'), 'bpm_form_definitions', ['workspace_id'], unique=False)
    op.create_table('bpm_process_definitions',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('bpmn_xml', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('process_config', sa.JSON(), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('form_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('instance_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bpm_process_definitions_key'), 'bpm_process_definitions', ['key'], unique=False)
    op.create_index(op.f('ix_bpm_process_definitions_workspace_id'), 'bpm_process_definitions', ['workspace_id'], unique=False)
    op.create_table('bpm_process_instances',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_definition_id', sa.Uuid(), nullable=False),
    sa.Column('process_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('process_version', sa.Integer(), nullable=False),
    sa.Column('business_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING', 'SUSPENDED', 'COMPLETED', 'REJECTED', 'CANCELLED', 'FAILED', name='processstatus'), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('current_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_task_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bpm_process_instances_business_key'), 'bpm_process_instances', ['business_key'], unique=False)
    op.create_index(op.f('ix_bpm_process_instances_process_definition_id'), 'bpm_process_instances', ['process_definition_id'], unique=False)
    op.create_index(op.f('ix_bpm_process_instances_process_key'), 'bpm_process_instances', ['process_key'], unique=False)
    op.create_index(op.f('ix_bpm_process_instances_status'), 'bpm_process_instances', ['status'], unique=False)
    op.create_index(op.f('ix_bpm_process_instances_workflow_run_id'), 'bpm_process_instances', ['workflow_run_id'], unique=False)
    op.create_index(op.f('ix_bpm_process_instances_workspace_id'), 'bpm_process_instances', ['workspace_id'], unique=False)
    op.create_table('bpm_tasks',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_instance_id', sa.Uuid(), nullable=False),
    sa.Column('task_def_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('task_type', sa.Enum('USER_TASK', 'SERVICE_TASK', 'SCRIPT_TASK', 'APPROVAL_TASK', name='tasktype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assignee', sa.Uuid(), nullable=True),
    sa.Column('candidate_users', sa.JSON(), nullable=True),
    sa.Column('candidate_groups', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED', 'TIMEOUT', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('form_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bpm_tasks_assignee'), 'bpm_tasks', ['assignee'], unique=False)
    op.create_index(op.f('ix_bpm_tasks_process_instance_id'), 'bpm_tasks', ['process_instance_id'], unique=False)
    op.create_index(op.f('ix_bpm_tasks_status'), 'bpm_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_bpm_tasks_workspace_id'), 'bpm_tasks', ['workspace_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('source_output', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('target_input', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_source_node_id'), 'connections', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_connections_target_node_id'), 'connections', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_connections_workflow_id'), 'connections', ['workflow_id'], unique=False)
    op.create_table('conversations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('end_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_application_id'), 'conversations', ['application_id'], unique=False)
    op.create_index(op.f('ix_conversations_end_user_id'), 'conversations', ['end_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_table('dataset_application_joins',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_application_joins_application_id'), 'dataset_application_joins', ['application_id'], unique=False)
    op.create_index(op.f('ix_dataset_application_joins_dataset_id'), 'dataset_application_joins', ['dataset_id'], unique=False)
    op.create_table('datasets',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('embedding_model_provider', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('retrieval_model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indexing_technique', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_index(op.f('ix_datasets_workspace_id'), 'datasets', ['workspace_id'], unique=False)
    op.create_table('document_segments',
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('index_node_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('index_node_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_by', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_segments_dataset_id'), 'document_segments', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_document_segments_document_id'), 'document_segments', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_segments_enabled'), 'document_segments', ['enabled'], unique=False)
    op.create_index(op.f('ix_document_segments_position'), 'document_segments', ['position'], unique=False)
    op.create_index(op.f('ix_document_segments_status'), 'document_segments', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('data_source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('data_source_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('indexing_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_by', sa.Uuid(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_archived'), 'documents', ['archived'], unique=False)
    op.create_index(op.f('ix_documents_data_source_type'), 'documents', ['data_source_type'], unique=False)
    op.create_index(op.f('ix_documents_dataset_id'), 'documents', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_documents_enabled'), 'documents', ['enabled'], unique=False)
    op.create_index(op.f('ix_documents_file_id'), 'documents', ['file_id'], unique=False)
    op.create_index(op.f('ix_documents_indexing_status'), 'documents', ['indexing_status'], unique=False)
    op.create_table('end_users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('external_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_end_users_external_user_id'), 'end_users', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_end_users_is_anonymous'), 'end_users', ['is_anonymous'], unique=False)
    op.create_index(op.f('ix_end_users_session_id'), 'end_users', ['session_id'], unique=False)
    op.create_index(op.f('ix_end_users_workspace_id'), 'end_users', ['workspace_id'], unique=False)
    op.create_table('execution_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_records_started_at'), 'execution_records', ['started_at'], unique=False)
    op.create_index(op.f('ix_execution_records_status'), 'execution_records', ['status'], unique=False)
    op.create_index(op.f('ix_execution_records_workflow_id'), 'execution_records', ['workflow_id'], unique=False)
    op.create_table('file_references',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('d', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mongo_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'd')
    )
    op.create_index(op.f('ix_file_references_file_id'), 'file_references', ['file_id'], unique=True)
    op.create_index(op.f('ix_file_references_storage_type'), 'file_references', ['storage_type'], unique=False)
    op.create_index(op.f('ix_file_references_uploaded_by'), 'file_references', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_file_references_workspace_id'), 'file_references', ['workspace_id'], unique=False)
    op.create_table('installed_plugins',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plugin_id', sa.Uuid(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('installed_by', sa.Uuid(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_plugins_installed_at'), 'installed_plugins', ['installed_at'], unique=False)
    op.create_index(op.f('ix_installed_plugins_installed_by'), 'installed_plugins', ['installed_by'], unique=False)
    op.create_index(op.f('ix_installed_plugins_is_enabled'), 'installed_plugins', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_installed_plugins_plugin_id'), 'installed_plugins', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_installed_plugins_workspace_id'), 'installed_plugins', ['workspace_id'], unique=False)
    op.create_table('llm_providers',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_providers_workspace_id'), 'llm_providers', ['workspace_id'], unique=False)
    op.create_table('message_annotations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('annotation_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('annotated_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_annotations_annotated_by'), 'message_annotations', ['annotated_by'], unique=False)
    op.create_index(op.f('ix_message_annotations_annotation_type'), 'message_annotations', ['annotation_type'], unique=False)
    op.create_index(op.f('ix_message_annotations_application_id'), 'message_annotations', ['application_id'], unique=False)
    op.create_index(op.f('ix_message_annotations_conversation_id'), 'message_annotations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_annotations_message_id'), 'message_annotations', ['message_id'], unique=False)
    op.create_table('message_feedbacks',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('end_user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_feedbacks_application_id'), 'message_feedbacks', ['application_id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_conversation_id'), 'message_feedbacks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_end_user_id'), 'message_feedbacks', ['end_user_id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_message_id'), 'message_feedbacks', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_rating'), 'message_feedbacks', ['rating'], unique=False)
    op.create_table('messages',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_provider', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_application_id'), 'messages', ['application_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_workflow_run_id'), 'messages', ['workflow_run_id'], unique=False)
    op.create_table('node_execution_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_record_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_execution_results_execution_record_id'), 'node_execution_results', ['execution_record_id'], unique=False)
    op.create_index(op.f('ix_node_execution_results_node_id'), 'node_execution_results', ['node_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_workflow_id'), 'nodes', ['workflow_id'], unique=False)
    op.create_table('organizations',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('password_resets',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.create_index(op.f('ix_password_resets_used'), 'password_resets', ['used'], unique=False)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('plugins',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('plugin_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('documentation_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugins_category'), 'plugins', ['category'], unique=False)
    op.create_index(op.f('ix_plugins_is_active'), 'plugins', ['is_active'], unique=False)
    op.create_index(op.f('ix_plugins_is_verified'), 'plugins', ['is_verified'], unique=False)
    op.create_index(op.f('ix_plugins_name'), 'plugins', ['name'], unique=True)
    op.create_index(op.f('ix_plugins_plugin_type'), 'plugins', ['plugin_type'], unique=False)
    op.create_table('prompt_template_versions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_template_versions_template_id'), 'prompt_template_versions', ['template_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_workspace_id'), 'prompt_templates', ['workspace_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('plan_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('billing_cycle', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('quota_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_type'), 'subscriptions', ['plan_type'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_workspace_id'), 'subscriptions', ['workspace_id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invitations_email'), 'team_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_team_invitations_invited_by'), 'team_invitations', ['invited_by'], unique=False)
    op.create_index(op.f('ix_team_invitations_status'), 'team_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_team_invitations_team_id'), 'team_invitations', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_token'), 'team_invitations', ['token'], unique=True)
    op.create_table('team_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_period_end'), 'usage_records', ['period_end'], unique=False)
    op.create_index(op.f('ix_usage_records_period_start'), 'usage_records', ['period_start'], unique=False)
    op.create_index(op.f('ix_usage_records_recorded_at'), 'usage_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_usage_records_resource_type'), 'usage_records', ['resource_type'], unique=False)
    op.create_index(op.f('ix_usage_records_subscription_id'), 'usage_records', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_records_workspace_id'), 'usage_records', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workflows',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_index(op.f('ix_workflows_workspace_id'), 'workflows', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.create_index(op.f('ix_workspaces_team_id'), 'workspaces', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_team_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_workflows_workspace_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_workspace_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_subscription_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_resource_type'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_recorded_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_period_start'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_period_end'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_team_invitations_token'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_team_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_status'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_invited_by'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_email'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_subscriptions_workspace_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_type'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_prompt_templates_workspace_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_prompt_template_versions_template_id'), table_name='prompt_template_versions')
    op.drop_table('prompt_template_versions')
    op.drop_index(op.f('ix_plugins_plugin_type'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_name'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_is_verified'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_is_active'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_category'), table_name='plugins')
    op.drop_table('plugins')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_used'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_nodes_workflow_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_node_execution_results_node_id'), table_name='node_execution_results')
    op.drop_index(op.f('ix_node_execution_results_execution_record_id'), table_name='node_execution_results')
    op.drop_table('node_execution_results')
    op.drop_index(op.f('ix_messages_workflow_run_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_application_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_message_feedbacks_rating'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_message_id'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_end_user_id'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_conversation_id'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_application_id'), table_name='message_feedbacks')
    op.drop_table('message_feedbacks')
    op.drop_index(op.f('ix_message_annotations_message_id'), table_name='message_annotations')
    op.drop_index(op.f('ix_message_annotations_conversation_id'), table_name='message_annotations')
    op.drop_index(op.f('ix_message_annotations_application_id'), table_name='message_annotations')
    op.drop_index(op.f('ix_message_annotations_annotation_type'), table_name='message_annotations')
    op.drop_index(op.f('ix_message_annotations_annotated_by'), table_name='message_annotations')
    op.drop_table('message_annotations')
    op.drop_index(op.f('ix_llm_providers_workspace_id'), table_name='llm_providers')
    op.drop_table('llm_providers')
    op.drop_index(op.f('ix_installed_plugins_workspace_id'), table_name='installed_plugins')
    op.drop_index(op.f('ix_installed_plugins_plugin_id'), table_name='installed_plugins')
    op.drop_index(op.f('ix_installed_plugins_is_enabled'), table_name='installed_plugins')
    op.drop_index(op.f('ix_installed_plugins_installed_by'), table_name='installed_plugins')
    op.drop_index(op.f('ix_installed_plugins_installed_at'), table_name='installed_plugins')
    op.drop_table('installed_plugins')
    op.drop_index(op.f('ix_file_references_workspace_id'), table_name='file_references')
    op.drop_index(op.f('ix_file_references_uploaded_by'), table_name='file_references')
    op.drop_index(op.f('ix_file_references_storage_type'), table_name='file_references')
    op.drop_index(op.f('ix_file_references_file_id'), table_name='file_references')
    op.drop_table('file_references')
    op.drop_index(op.f('ix_execution_records_workflow_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_status'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_started_at'), table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_index(op.f('ix_end_users_workspace_id'), table_name='end_users')
    op.drop_index(op.f('ix_end_users_session_id'), table_name='end_users')
    op.drop_index(op.f('ix_end_users_is_anonymous'), table_name='end_users')
    op.drop_index(op.f('ix_end_users_external_user_id'), table_name='end_users')
    op.drop_table('end_users')
    op.drop_index(op.f('ix_documents_indexing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_enabled'), table_name='documents')
    op.drop_index(op.f('ix_documents_dataset_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_data_source_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_archived'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_segments_status'), table_name='document_segments')
    op.drop_index(op.f('ix_document_segments_position'), table_name='document_segments')
    op.drop_index(op.f('ix_document_segments_enabled'), table_name='document_segments')
    op.drop_index(op.f('ix_document_segments_document_id'), table_name='document_segments')
    op.drop_index(op.f('ix_document_segments_dataset_id'), table_name='document_segments')
    op.drop_table('document_segments')
    op.drop_index(op.f('ix_datasets_workspace_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_dataset_application_joins_dataset_id'), table_name='dataset_application_joins')
    op.drop_index(op.f('ix_dataset_application_joins_application_id'), table_name='dataset_application_joins')
    op.drop_table('dataset_application_joins')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_end_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_application_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_connections_workflow_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_target_node_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_source_node_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_bpm_tasks_workspace_id'), table_name='bpm_tasks')
    op.drop_index(op.f('ix_bpm_tasks_status'), table_name='bpm_tasks')
    op.drop_index(op.f('ix_bpm_tasks_process_instance_id'), table_name='bpm_tasks')
    op.drop_index(op.f('ix_bpm_tasks_assignee'), table_name='bpm_tasks')
    op.drop_table('bpm_tasks')
    op.drop_index(op.f('ix_bpm_process_instances_workspace_id'), table_name='bpm_process_instances')
    op.drop_index(op.f('ix_bpm_process_instances_workflow_run_id'), table_name='bpm_process_instances')
    op.drop_index(op.f('ix_bpm_process_instances_status'), table_name='bpm_process_instances')
    op.drop_index(op.f('ix_bpm_process_instances_process_key'), table_name='bpm_process_instances')
    op.drop_index(op.f('ix_bpm_process_instances_process_definition_id'), table_name='bpm_process_instances')
    op.drop_index(op.f('ix_bpm_process_instances_business_key'), table_name='bpm_process_instances')
    op.drop_table('bpm_process_instances')
    op.drop_index(op.f('ix_bpm_process_definitions_workspace_id'), table_name='bpm_process_definitions')
    op.drop_index(op.f('ix_bpm_process_definitions_key'), table_name='bpm_process_definitions')
    op.drop_table('bpm_process_definitions')
    op.drop_index(op.f('ix_bpm_form_definitions_workspace_id'), table_name='bpm_form_definitions')
    op.drop_index(op.f('ix_bpm_form_definitions_key'), table_name='bpm_form_definitions')
    op.drop_table('bpm_form_definitions')
    op.drop_index(op.f('ix_bpm_form_data_workspace_id'), table_name='bpm_form_data')
    op.drop_index(op.f('ix_bpm_form_data_task_id'), table_name='bpm_form_data')
    op.drop_index(op.f('ix_bpm_form_data_process_instance_id'), table_name='bpm_form_data')
    op.drop_table('bpm_form_data')
    op.drop_index(op.f('ix_bpm_approvals_workspace_id'), table_name='bpm_approvals')
    op.drop_index(op.f('ix_bpm_approvals_task_id'), table_name='bpm_approvals')
    op.drop_index(op.f('ix_bpm_approvals_process_instance_id'), table_name='bpm_approvals')
    op.drop_index(op.f('ix_bpm_approvals_approver_id'), table_name='bpm_approvals')
    op.drop_table('bpm_approvals')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_workspace_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_workflow_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_application_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
