"""delete Workspace and workspace account Fleid AuditMixin

Revision ID: 5b7ba9e61d50
Revises: c89bb70366c7
Create Date: 2026-01-09 11:01:57.743232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7ba9e61d50'
down_revision: Union[str, Sequence[str], None] = 'c89bb70366c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_accounts', 'created_by')
    op.drop_column('workspace_accounts', 'updated_by')
    op.drop_column('workspaces', 'created_by')
    op.drop_column('workspaces', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workspaces', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'workspaces', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'workspace_accounts', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'workspace_accounts',
        sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
