"""setting invited_by in uuid or None by workspace_account

Revision ID: 8ea0549bc3e0
Revises: 5b7ba9e61d50
Create Date: 2026-01-09 11:22:44.368275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea0549bc3e0'
down_revision: Union[str, Sequence[str], None] = '5b7ba9e61d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_accounts', 'invited_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_accounts', 'invited_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
