"""add_workspace_id_to_teams_and_update_tenant_schema

Revision ID: c89bb70366c7
Revises: add_soft_delete_001
Create Date: 2026-01-08 16:47:19.516793

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c89bb70366c7'
down_revision: Union[str, Sequence[str], None] = 'add_soft_delete_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'workspace_accounts',
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column('updated_by', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('workspace_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column(
            'role',
            sa.Enum(
                'OWNER', 'ADMIN', 'EDITOR', 'NORMAL', 'DATASET_OPERATOR', name='tenantaccountrole'
            ),
            nullable=False,
        ),
        sa.Column('current', sa.Boolean(), nullable=False),
        sa.Column('invited_by', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user'),
    )
    op.create_index(
        op.f('ix_workspace_accounts_user_id'), 'workspace_accounts', ['user_id'], unique=False
    )
    op.create_index(
        op.f('ix_workspace_accounts_workspace_id'),
        'workspace_accounts',
        ['workspace_id'],
        unique=False,
    )
    op.alter_column(
        'bpm_form_definitions',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_bpm_form_definitions_deleted_at'), table_name='bpm_form_definitions')
    op.drop_index(op.f('ix_bpm_form_definitions_is_deleted'), table_name='bpm_form_definitions')
    op.drop_column('bpm_tasks', 'candidate_groups')
    op.alter_column(
        'conversations',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_deleted'), table_name='conversations')
    op.alter_column(
        'document_segments',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_document_segments_deleted_at'), table_name='document_segments')
    op.drop_index(op.f('ix_document_segments_is_deleted'), table_name='document_segments')
    op.alter_column(
        'documents',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.alter_column(
        'end_users',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_end_users_deleted_at'), table_name='end_users')
    op.drop_index(op.f('ix_end_users_is_deleted'), table_name='end_users')
    op.alter_column(
        'file_references',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_file_references_deleted_at'), table_name='file_references')
    op.drop_index(op.f('ix_file_references_is_deleted'), table_name='file_references')
    op.alter_column(
        'installed_plugins',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_installed_plugins_deleted_at'), table_name='installed_plugins')
    op.drop_index(op.f('ix_installed_plugins_is_deleted'), table_name='installed_plugins')
    op.alter_column(
        'messages',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_deleted'), table_name='messages')
    op.alter_column(
        'nodes',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_nodes_deleted_at'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_is_deleted'), table_name='nodes')
    op.alter_column(
        'prompt_template_versions',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f('ix_prompt_template_versions_deleted_at'), table_name='prompt_template_versions'
    )
    op.drop_index(
        op.f('ix_prompt_template_versions_is_deleted'), table_name='prompt_template_versions'
    )
    op.drop_column('team_members', 'role')

    # 首先创建 enum 类型
    op.execute("CREATE TYPE workspaceplan AS ENUM ('FREE', 'PRO', 'ENTERPRISE')")
    op.execute("CREATE TYPE workspacestatus AS ENUM ('NORMAL', 'ARCHIVE')")

    # 然后添加 workspaces 的新列（先作为 nullable，然后设置默认值）
    op.add_column(
        'workspaces',
        sa.Column(
            'encrypt_public_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True
        ),
    )
    op.add_column(
        'workspaces',
        sa.Column(
            'plan', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='workspaceplan'), nullable=True
        ),
    )
    op.add_column(
        'workspaces',
        sa.Column('status', sa.Enum('NORMAL', 'ARCHIVE', name='workspacestatus'), nullable=True),
    )

    # 为现有的 workspaces 记录设置默认值
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        UPDATE workspaces
        SET encrypt_public_key = '',
            plan = 'FREE',
            status = 'NORMAL'
        WHERE encrypt_public_key IS NULL
           OR plan IS NULL
           OR status IS NULL
    """)
    )

    # 现在将列改为 NOT NULL
    op.alter_column('workspaces', 'encrypt_public_key', nullable=False)
    op.alter_column('workspaces', 'plan', nullable=False)
    op.alter_column('workspaces', 'status', nullable=False)

    op.drop_index(op.f('ix_workspaces_team_id'), table_name='workspaces')
    op.drop_column('workspaces', 'team_id')

    # 现在处理 teams 表的 workspace_id 列
    # 先添加为 nullable
    op.add_column('teams', sa.Column('workspace_id', sa.Uuid(), nullable=True))

    # 为现有的 teams 记录创建默认的 workspace
    connection = op.get_bind()
    result = connection.execute(sa.text('SELECT COUNT(*) FROM teams'))
    team_count = result.scalar()

    if team_count > 0:
        # 创建一个默认的 workspace 用于现有的 teams
        default_workspace_id = connection.execute(
            sa.text("""
            INSERT INTO workspaces (id, name, description, created_by, created_at, updated_at,
                                  encrypt_public_key, plan, status, is_deleted, deleted_at)
            SELECT
                gen_random_uuid(),
                'Default Workspace',
                'Auto-created workspace for existing teams',
                created_by,
                NOW(),
                NOW(),
                '',
                'FREE',
                'NORMAL',
                false,
                NULL
            FROM teams
            LIMIT 1
            RETURNING id
        """)
        ).scalar()

        # 更新所有现有的 teams 记录使用这个默认 workspace
        connection.execute(
            sa.text(f"""
            UPDATE teams
            SET workspace_id = '{default_workspace_id}'
            WHERE workspace_id IS NULL
        """)
        )

    # 现在将列改为 NOT NULL
    op.alter_column('teams', 'workspace_id', nullable=False)
    op.create_index(op.f('ix_teams_workspace_id'), 'teams', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workspaces', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_index(op.f('ix_workspaces_team_id'), 'workspaces', ['team_id'], unique=False)
    op.drop_column('workspaces', 'status')
    op.drop_column('workspaces', 'plan')
    op.drop_column('workspaces', 'encrypt_public_key')
    op.drop_index(op.f('ix_teams_workspace_id'), table_name='teams')
    op.drop_column('teams', 'workspace_id')
    op.add_column(
        'team_members',
        sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f('ix_prompt_template_versions_is_deleted'),
        'prompt_template_versions',
        ['is_deleted'],
        unique=False,
    )
    op.create_index(
        op.f('ix_prompt_template_versions_deleted_at'),
        'prompt_template_versions',
        ['deleted_at'],
        unique=False,
    )
    op.alter_column(
        'prompt_template_versions',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(op.f('ix_nodes_is_deleted'), 'nodes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_nodes_deleted_at'), 'nodes', ['deleted_at'], unique=False)
    op.alter_column(
        'nodes',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(op.f('ix_messages_is_deleted'), 'messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.alter_column(
        'messages',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(
        op.f('ix_installed_plugins_is_deleted'), 'installed_plugins', ['is_deleted'], unique=False
    )
    op.create_index(
        op.f('ix_installed_plugins_deleted_at'), 'installed_plugins', ['deleted_at'], unique=False
    )
    op.alter_column(
        'installed_plugins',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(
        op.f('ix_file_references_is_deleted'), 'file_references', ['is_deleted'], unique=False
    )
    op.create_index(
        op.f('ix_file_references_deleted_at'), 'file_references', ['deleted_at'], unique=False
    )
    op.alter_column(
        'file_references',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(op.f('ix_end_users_is_deleted'), 'end_users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_end_users_deleted_at'), 'end_users', ['deleted_at'], unique=False)
    op.alter_column(
        'end_users',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.alter_column(
        'documents',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(
        op.f('ix_document_segments_is_deleted'), 'document_segments', ['is_deleted'], unique=False
    )
    op.create_index(
        op.f('ix_document_segments_deleted_at'), 'document_segments', ['deleted_at'], unique=False
    )
    op.alter_column(
        'document_segments',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_index(
        op.f('ix_conversations_is_deleted'), 'conversations', ['is_deleted'], unique=False
    )
    op.create_index(
        op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False
    )
    op.alter_column(
        'conversations',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.add_column(
        'bpm_tasks',
        sa.Column(
            'candidate_groups',
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f('ix_bpm_form_definitions_is_deleted'),
        'bpm_form_definitions',
        ['is_deleted'],
        unique=False,
    )
    op.create_index(
        op.f('ix_bpm_form_definitions_deleted_at'),
        'bpm_form_definitions',
        ['deleted_at'],
        unique=False,
    )
    op.alter_column(
        'bpm_form_definitions',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_workspace_accounts_workspace_id'), table_name='workspace_accounts')
    op.drop_index(op.f('ix_workspace_accounts_user_id'), table_name='workspace_accounts')
    op.drop_table('workspace_accounts')
    # ### end Alembic commands ###
